image: alpine:latest

pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  - mkdir .public
  - cp -a /medata_backend/docs/ .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
